include:
- project: stig/inspec-scanning-integration
  ref: 1.1.11
  file: templates/templates.yml

before_script:
  - echo "SCV Pipeline for PostgreSQL 9.X"

stages:
  - check
  - lint
  - exec
  - publish

check PostgreSQL_9.X:
  extends: .ci:stage:check:inspec

lint PostgreSQL_9.X:
  extends: .ci:stage:lint:inspec

exec PostgreSQL_9.X:
  extends: .ci:stage:exec:inspec
  variables:
    TARGET: 'rep.dsolab.io/baselines/postgres9.6_baseline:1.0'

publish PostgreSQL_9.X:
  extends: .ci:stage:publish:inspec:artifacts
  dependencies:
  - check PostgreSQL_9.X
  - lint PostgreSQL_9.X
  - exec PostgreSQL_9.X

sync:
  extends: .ci:stage:publish:inspec:sync
  variables:
    SYNC_REPO: "repo1.dso.mil/disa/inspec/oracle/19c.git"
    SYNC_TOKEN: $IR1_POSTGRES_9X
