include:
- project: stig/inspec-scanning-integration
  ref: 1.0.0
  file: templates/dependencies.yml

before_script:
  - echo "SCV Pipeline for PostgreSQL 9.X"

stages:
  - check
  - lint   
 
check PostgreSQL_9.X:
  extends: .ci:stage:check:inspec

lint PostgreSQL_9.X:
  extends: .ci:stage:lint:inspec
